name: Gatsby Publish GH-Pages

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Gatsby Publish
        uses: enriikke/gatsby-gh-pages-action@v2.2.0
        with:
          access-token: ${{ secrets.DEPLOY_TO_PAGES_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
